vcom common/utilities.vhd
vcom common/txt_util.vhd 
vcom common/MAST_config.vhd
vcom Examples/JTAG/JTAG_configuration.vhd  
vcom common/types.vhd
vcom Examples/JTAG/bs_elements.vhd  
vcom common/JTAG_package.vhd  
vcom common/exchange_registers.vhd
vcom Examples/JTAG/slave_tap.vhd  
vcom Examples/JTAG/MIB_tutorial.vhd 
vcom Examples/JTAG/tutorial_1.vhd
vcom scan_encryption/trivium.vhd

vcom scan_authentication/Example/cSIB.vhd
vcom scan_authentication/SSAK/data_types.vhd
vcom scan_authentication/SSAK/fonctions.vhd
vcom scan_authentication/SSAK/FSM2.vhd
vcom scan_authentication/CryptoProc/AES/AXISbuffer.vhd
vcom scan_authentication/SSAK/AXIS_ip/axismux.vhd
vcom scan_authentication/SSAK/TNRGfx.vhd
vcom scan_authentication/SSAK/l_key.vhd
vcom scan_authentication/SSAK/sscdriver.vhd
vcom scan_authentication/SSAK/AXIS_ip/axisdemux.vhd
vcom scan_authentication/SSAK/AXIS_ip/compres.vhd
vcom scan_authentication/SSAK/AXIS_ip/interface.vhd
vcom scan_authentication/SSAK/SSAK.vhd
vcom scan_authentication/CryptoProc/AES/aes128Pkg.vhd
vcom scan_authentication/CryptoProc/AES/sbox.vhd
vcom scan_authentication/CryptoProc/AES/subWord.vhd
vcom scan_authentication/CryptoProc/AES/keyExpansion.vhd
vcom scan_authentication/CryptoProc/AES/subMatrix.vhd
vcom scan_authentication/CryptoProc/AES/mixColumn.vhd
vcom scan_authentication/CryptoProc/AES/mixMatrix.vhd
vcom scan_authentication/CryptoProc/AES/cipherRound.vhd
vcom scan_authentication/CryptoProc/AES/aes128.vhd
vcom scan_authentication/CryptoProc/AES/AES128_AXIS_Wrapper.vhd
vcom scan_authentication/Example/ScanSegment.vhd
vcom scan_authentication/Example/PRNG128.vhd
vcom scan_authentication/Example/PRNG_gest.vhd
vcom scan_authentication/Example/topTestDesing.vhd

vcom Examples/JTAG/SUT.vhd 
vcom AI_for_simulation/master_tapfsm.vhd
vcom AI_for_simulation/SVF_Master_TAP.vhd  
vcom scan_encryption/SVF_Simuation_top_encryption.vhd

vcom scan_authentication/Example/bench/benchTopDemo.vhd
vcom Examples/JTAG/SVF_Simuation_top.vhd
