#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#

.RECIPEPREFIX = >

WORKDIR = `pwd`

CC = gcc-4.9
CXX = g++-4.9
AR = ar-4.9
LD = g++-4.9
WINDRES = windres

INC = -Iinclude -Ipublic_include
WARNINGS = -Wall -Wextra -Wpedantic  -Wnon-virtual-dtor -Wredundant-decls -Wundef -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default
CFLAGS = $(WARNINGS) -std=c++14 -fPIC
RESINC =
LIBDIR =
LIB =
LDFLAGS =

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -DBUILD_DLL
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS) -Wl,--dll
OBJDIR_DEBUG = ../obj/debug
DEP_DEBUG =
OUT_DEBUG = ../bin/debug/Lib.so

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -DBUILD_DLL
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s -Wl,--dll
OBJDIR_RELEASE = ../obj/release
DEP_RELEASE =
OUT_RELEASE = ../bin/release/Lib.so

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/AccessInterface.o                 \
            $(OBJDIR_DEBUG)/src/AccessInterfaceProtocol_1149_1.o  \
            $(OBJDIR_DEBUG)/src/BinaryVector.o                    \
            $(OBJDIR_DEBUG)/src/Chain.o                           \
            $(OBJDIR_DEBUG)/src/DefaultBinaryPathSelector.o       \
            $(OBJDIR_DEBUG)/src/GmlPrinterVisitor.o               \
            $(OBJDIR_DEBUG)/src/ConfigureVisitor.o                \
            $(OBJDIR_DEBUG)/src/Linker.o                          \
            $(OBJDIR_DEBUG)/src/ParentNode.o                      \
            $(OBJDIR_DEBUG)/src/PrettyPrinterVisitor.o            \
            $(OBJDIR_DEBUG)/src/Register.o                        \
            $(OBJDIR_DEBUG)/src/SVFVector.o                       \
            $(OBJDIR_DEBUG)/src/SystemModel.o                     \
            $(OBJDIR_DEBUG)/src/SystemModelCheckerVisitor.o       \
            $(OBJDIR_DEBUG)/src/SystemModelCheckResult.o          \
            $(OBJDIR_DEBUG)/src/SystemModelNode.o                 \
            $(OBJDIR_DEBUG)/src/Utility.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/AccessInterface.o               \
            $(OBJDIR_RELEASE)/src/AccessInterfaceProtocol_1149_1.o  \
            $(OBJDIR_RELEASE)/src/BinaryVector.o                    \
            $(OBJDIR_RELEASE)/src/Chain.o                           \
            $(OBJDIR_RELEASE)/src/DefaultBinaryPathSelector.o       \
            $(OBJDIR_RELEASE)/src/GmlPrinterVisitor.o               \
            $(OBJDIR_RELEASE)/src/ConfigureVisitor.o                \
            $(OBJDIR_RELEASE)/src/Linker.o                          \
            $(OBJDIR_RELEASE)/src/ParentNode.o                      \
            $(OBJDIR_RELEASE)/src/PrettyPrinterVisitor.o            \
            $(OBJDIR_RELEASE)/src/Register.o                        \
            $(OBJDIR_RELEASE)/src/SVFVector.o                       \
            $(OBJDIR_RELEASE)/src/SystemModel.o                     \
            $(OBJDIR_RELEASE)/src/SystemModelCheckerVisitor.o       \
            $(OBJDIR_RELEASE)/src/SystemModelCheckResult.o          \
            $(OBJDIR_RELEASE)/src/SystemModelNode.o                 \
            $(OBJDIR_RELEASE)/src/Utility.o

all: debug release

clean: clean_debug clean_release

before_debug:
> test -d ../bin/debug || mkdir -p ../bin/debug
> test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug:

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
> $(LD) -shared $(LIBDIR_DEBUG) $(OBJ_DEBUG)  -o $(OUT_DEBUG) $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/AccessInterface.o: src/AccessInterface.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/AccessInterface.cpp -o $(OBJDIR_DEBUG)/src/AccessInterface.o

$(OBJDIR_DEBUG)/src/AccessInterfaceProtocol_1149_1.o: src/AccessInterfaceProtocol_1149_1.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/AccessInterfaceProtocol_1149_1.cpp -o $(OBJDIR_DEBUG)/src/AccessInterfaceProtocol_1149_1.o

$(OBJDIR_DEBUG)/src/BinaryVector.o: src/BinaryVector.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/BinaryVector.cpp -o $(OBJDIR_DEBUG)/src/BinaryVector.o

$(OBJDIR_DEBUG)/src/Chain.o: src/Chain.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Chain.cpp -o $(OBJDIR_DEBUG)/src/Chain.o

$(OBJDIR_DEBUG)/src/DefaultBinaryPathSelector.o: src/DefaultBinaryPathSelector.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DefaultBinaryPathSelector.cpp -o $(OBJDIR_DEBUG)/src/DefaultBinaryPathSelector.o

$(OBJDIR_DEBUG)/src/GmlPrinterVisitor.o: src/GmlPrinterVisitor.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GmlPrinterVisitor.cpp -o $(OBJDIR_DEBUG)/src/GmlPrinterVisitor.o

$(OBJDIR_DEBUG)/src/ConfigureVisitor.o: src/ConfigureVisitor.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ConfigureVisitor.cpp -o $(OBJDIR_DEBUG)/src/ConfigureVisitor.o

$(OBJDIR_DEBUG)/src/Linker.o: src/Linker.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Linker.cpp -o $(OBJDIR_DEBUG)/src/Linker.o

$(OBJDIR_DEBUG)/src/ParentNode.o: src/ParentNode.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ParentNode.cpp -o $(OBJDIR_DEBUG)/src/ParentNode.o

$(OBJDIR_DEBUG)/src/PrettyPrinterVisitor.o: src/PrettyPrinterVisitor.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/PrettyPrinterVisitor.cpp -o $(OBJDIR_DEBUG)/src/PrettyPrinterVisitor.o

$(OBJDIR_DEBUG)/src/Register.o: src/Register.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Register.cpp -o $(OBJDIR_DEBUG)/src/Register.o

$(OBJDIR_DEBUG)/src/SVFVector.o: src/SVFVector.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SVFVector.cpp -o $(OBJDIR_DEBUG)/src/SVFVector.o

$(OBJDIR_DEBUG)/src/SystemModel.o: src/SystemModel.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SystemModel.cpp -o $(OBJDIR_DEBUG)/src/SystemModel.o

$(OBJDIR_DEBUG)/src/SystemModelCheckerVisitor.o: src/SystemModelCheckerVisitor.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SystemModelCheckerVisitor.cpp -o $(OBJDIR_DEBUG)/src/SystemModelCheckerVisitor.o

$(OBJDIR_DEBUG)/src/SystemModelCheckResult.o: src/SystemModelCheckResult.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SystemModelCheckResult.cpp -o $(OBJDIR_DEBUG)/src/SystemModelCheckResult.o

$(OBJDIR_DEBUG)/src/SystemModelNode.o: src/SystemModelNode.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SystemModelNode.cpp -o $(OBJDIR_DEBUG)/src/SystemModelNode.o

$(OBJDIR_DEBUG)/src/Utility.o: src/Utility.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Utility.cpp -o $(OBJDIR_DEBUG)/src/Utility.o

clean_debug:
> rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
> rm -rf ../bin/debug
> rm -rf $(OBJDIR_DEBUG)/src

before_release:
> test -d ../bin/release || mkdir -p ../bin/release
> test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release:

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
> $(LD) -shared $(LIBDIR_RELEASE) $(OBJ_RELEASE)  -o $(OUT_RELEASE) $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/AccessInterface.o: src/AccessInterface.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/AccessInterface.cpp -o $(OBJDIR_RELEASE)/src/AccessInterface.o

$(OBJDIR_RELEASE)/src/AccessInterfaceProtocol_1149_1.o: src/AccessInterfaceProtocol_1149_1.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/AccessInterfaceProtocol_1149_1.cpp -o $(OBJDIR_RELEASE)/src/AccessInterfaceProtocol_1149_1.o

$(OBJDIR_RELEASE)/src/BinaryVector.o: src/BinaryVector.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/BinaryVector.cpp -o $(OBJDIR_RELEASE)/src/BinaryVector.o

$(OBJDIR_RELEASE)/src/Chain.o: src/Chain.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Chain.cpp -o $(OBJDIR_RELEASE)/src/Chain.o

$(OBJDIR_RELEASE)/src/DefaultBinaryPathSelector.o: src/DefaultBinaryPathSelector.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DefaultBinaryPathSelector.cpp -o $(OBJDIR_RELEASE)/src/DefaultBinaryPathSelector.o

$(OBJDIR_RELEASE)/src/GmlPrinterVisitor.o: src/GmlPrinterVisitor.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GmlPrinterVisitor.cpp -o $(OBJDIR_RELEASE)/src/GmlPrinterVisitor.o

$(OBJDIR_RELEASE)/src/ConfigureVisitor.o: src/ConfigureVisitor.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ConfigureVisitor.cpp -o $(OBJDIR_RELEASE)/src/ConfigureVisitor.o

$(OBJDIR_RELEASE)/src/Linker.o: src/Linker.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Linker.cpp -o $(OBJDIR_RELEASE)/src/Linker.o

$(OBJDIR_RELEASE)/src/ParentNode.o: src/ParentNode.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ParentNode.cpp -o $(OBJDIR_RELEASE)/src/ParentNode.o

$(OBJDIR_RELEASE)/src/PrettyPrinterVisitor.o: src/PrettyPrinterVisitor.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/PrettyPrinterVisitor.cpp -o $(OBJDIR_RELEASE)/src/PrettyPrinterVisitor.o

$(OBJDIR_RELEASE)/src/Register.o: src/Register.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Register.cpp -o $(OBJDIR_RELEASE)/src/Register.o

$(OBJDIR_RELEASE)/src/SVFVector.o: src/SVFVector.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SVFVector.cpp -o $(OBJDIR_RELEASE)/src/SVFVector.o

$(OBJDIR_RELEASE)/src/SystemModel.o: src/SystemModel.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SystemModel.cpp -o $(OBJDIR_RELEASE)/src/SystemModel.o

$(OBJDIR_RELEASE)/src/SystemModelCheckerVisitor.o: src/SystemModelCheckerVisitor.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SystemModelCheckerVisitor.cpp -o $(OBJDIR_RELEASE)/src/SystemModelCheckerVisitor.o

$(OBJDIR_RELEASE)/src/SystemModelCheckResult.o: src/SystemModelCheckResult.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SystemModelCheckResult.cpp -o $(OBJDIR_RELEASE)/src/SystemModelCheckResult.o

$(OBJDIR_RELEASE)/src/SystemModelNode.o: src/SystemModelNode.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SystemModelNode.cpp -o $(OBJDIR_RELEASE)/src/SystemModelNode.o

$(OBJDIR_RELEASE)/src/Utility.o: src/Utility.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Utility.cpp -o $(OBJDIR_RELEASE)/src/Utility.o

clean_release:
> rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
> rm -rf ../bin/release
> rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

