#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = -I..\\cxxtest -I..\\Lib\\include -I..\\Lib\\public_include -ICxxTest_Traits
CFLAGS = -Wnon-virtual-dtor -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -pedantic-errors -pedantic -w -Wfatal-errors -Wextra -fexceptions -std=c++14 -DCXXTEST_HAVE_EH -DCXXTEST_HAVE_STD -DCXXTEST_PARTIAL_TEMPLATE_SPECIALIZATION
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)..\bin\Debug\libLib.a
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = ..\\obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = ..\\bin\\Debug\\Lib_UT.exe

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)..\bin\Release\libLib.a
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = ..\\obj\\Release
DEP_RELEASE = 
OUT_RELEASE = ..\\bin\\Release\\Lib_UT.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\Generated\\Runner.o $(OBJDIR_DEBUG)\\SystemModel\\UT_DefaultBinaryPathSelector.o $(OBJDIR_DEBUG)\\SystemModel\\UT_GmlPrinterVisitor.o $(OBJDIR_DEBUG)\\SystemModel\\UT_PrettyPrinterVisitor.o $(OBJDIR_DEBUG)\\SystemModel\\UT_Register.o $(OBJDIR_DEBUG)\\Utility\\UT_BinaryVector.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\Generated\\Runner.o $(OBJDIR_RELEASE)\\SystemModel\\UT_DefaultBinaryPathSelector.o $(OBJDIR_RELEASE)\\SystemModel\\UT_GmlPrinterVisitor.o $(OBJDIR_RELEASE)\\SystemModel\\UT_PrettyPrinterVisitor.o $(OBJDIR_RELEASE)\\SystemModel\\UT_Register.o $(OBJDIR_RELEASE)\\Utility\\UT_BinaryVector.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	mingw32-make.exe -f runner.mak
	cmd /c if not exist ..\\bin\\Debug md ..\\bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG)\\Generated md $(OBJDIR_DEBUG)\\Generated
	cmd /c if not exist $(OBJDIR_DEBUG)\\SystemModel md $(OBJDIR_DEBUG)\\SystemModel
	cmd /c if not exist $(OBJDIR_DEBUG)\\Utility md $(OBJDIR_DEBUG)\\Utility

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\Generated\\Runner.o: Generated\\Runner.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Generated\\Runner.cpp -o $(OBJDIR_DEBUG)\\Generated\\Runner.o

$(OBJDIR_DEBUG)\\SystemModel\\UT_DefaultBinaryPathSelector.o: SystemModel\\UT_DefaultBinaryPathSelector.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel\\UT_DefaultBinaryPathSelector.cpp -o $(OBJDIR_DEBUG)\\SystemModel\\UT_DefaultBinaryPathSelector.o

$(OBJDIR_DEBUG)\\SystemModel\\UT_GmlPrinterVisitor.o: SystemModel\\UT_GmlPrinterVisitor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel\\UT_GmlPrinterVisitor.cpp -o $(OBJDIR_DEBUG)\\SystemModel\\UT_GmlPrinterVisitor.o

$(OBJDIR_DEBUG)\\SystemModel\\UT_PrettyPrinterVisitor.o: SystemModel\\UT_PrettyPrinterVisitor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel\\UT_PrettyPrinterVisitor.cpp -o $(OBJDIR_DEBUG)\\SystemModel\\UT_PrettyPrinterVisitor.o

$(OBJDIR_DEBUG)\\SystemModel\\UT_Register.o: SystemModel\\UT_Register.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel\\UT_Register.cpp -o $(OBJDIR_DEBUG)\\SystemModel\\UT_Register.o

$(OBJDIR_DEBUG)\\Utility\\UT_BinaryVector.o: Utility\\UT_BinaryVector.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Utility\\UT_BinaryVector.cpp -o $(OBJDIR_DEBUG)\\Utility\\UT_BinaryVector.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd ..\\bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)\\Generated
	cmd /c rd $(OBJDIR_DEBUG)\\SystemModel
	cmd /c rd $(OBJDIR_DEBUG)\\Utility

before_release: 
	cmd /c if not exist ..\\bin\\Release md ..\\bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE)\\Generated md $(OBJDIR_RELEASE)\\Generated
	cmd /c if not exist $(OBJDIR_RELEASE)\\SystemModel md $(OBJDIR_RELEASE)\\SystemModel
	cmd /c if not exist $(OBJDIR_RELEASE)\\Utility md $(OBJDIR_RELEASE)\\Utility

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\Generated\\Runner.o: Generated\\Runner.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Generated\\Runner.cpp -o $(OBJDIR_RELEASE)\\Generated\\Runner.o

$(OBJDIR_RELEASE)\\SystemModel\\UT_DefaultBinaryPathSelector.o: SystemModel\\UT_DefaultBinaryPathSelector.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel\\UT_DefaultBinaryPathSelector.cpp -o $(OBJDIR_RELEASE)\\SystemModel\\UT_DefaultBinaryPathSelector.o

$(OBJDIR_RELEASE)\\SystemModel\\UT_GmlPrinterVisitor.o: SystemModel\\UT_GmlPrinterVisitor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel\\UT_GmlPrinterVisitor.cpp -o $(OBJDIR_RELEASE)\\SystemModel\\UT_GmlPrinterVisitor.o

$(OBJDIR_RELEASE)\\SystemModel\\UT_PrettyPrinterVisitor.o: SystemModel\\UT_PrettyPrinterVisitor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel\\UT_PrettyPrinterVisitor.cpp -o $(OBJDIR_RELEASE)\\SystemModel\\UT_PrettyPrinterVisitor.o

$(OBJDIR_RELEASE)\\SystemModel\\UT_Register.o: SystemModel\\UT_Register.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel\\UT_Register.cpp -o $(OBJDIR_RELEASE)\\SystemModel\\UT_Register.o

$(OBJDIR_RELEASE)\\Utility\\UT_BinaryVector.o: Utility\\UT_BinaryVector.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Utility\\UT_BinaryVector.cpp -o $(OBJDIR_RELEASE)\\Utility\\UT_BinaryVector.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd ..\\bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)\\Generated
	cmd /c rd $(OBJDIR_RELEASE)\\SystemModel
	cmd /c rd $(OBJDIR_RELEASE)\\Utility

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

