#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#

.RECIPEPREFIX = >

WORKDIR = `pwd`

CC = gcc-4.9
CXX = g++-4.9
AR = ar-4.9
LD = g++-4.9
WINDRES = windres

INC = -I../cxxtest -I../Lib/include -I../Lib/public_include -ICxxTest_Traits -IUT_Helpers
WARNINGS = -Wall -Wextra -Wpedantic  -Wnon-virtual-dtor -Wredundant-decls -Wundef -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default
CFLAGS =  $(WARNINGS) -fexceptions -std=c++14 -DCXXTEST_HAVE_EH -DCXXTEST_HAVE_STD -DCXXTEST_PARTIAL_TEMPLATE_SPECIALIZATION
RESINC =
LIBDIR =
LIB =
LDFLAGS =

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB) ../bin/debug/Lib.so
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = ../obj/debug
DEP_DEBUG =
OUT_DEBUG = ../bin/debug/Lib_UT

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)../bin/release/Lib.so
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = ../obj/release
DEP_RELEASE =
OUT_RELEASE = ../bin/release/Lib_UT

OBJ_DEBUG = \
            $(OBJDIR_DEBUG)/Utility/UT_Utility.o                           \
            $(OBJDIR_DEBUG)/Utility/UT_SVFVector.o                         \
            $(OBJDIR_DEBUG)/Utility/UT_BinaryVector.o                      \
            $(OBJDIR_DEBUG)/UT_Helpers/UT_SystemModelBuilder.o             \
            $(OBJDIR_DEBUG)/UT_Helpers/SystemModelBuilder.o                \
            $(OBJDIR_DEBUG)/SystemModel/UT_SystemModel.o                   \
            $(OBJDIR_DEBUG)/SystemModel/UT_SystemModelCheckerVisitor.o     \
            $(OBJDIR_DEBUG)/SystemModel/UT_Register.o                      \
            $(OBJDIR_DEBUG)/SystemModel/UT_SystemModelNode.o               \
            $(OBJDIR_DEBUG)/SystemModel/UT_PrettyPrinterVisitor.o          \
            $(OBJDIR_DEBUG)/SystemModel/UT_GmlPrinterVisitor.o             \
            $(OBJDIR_DEBUG)/SystemModel/UT_ConfigureVisitor.o              \
            $(OBJDIR_DEBUG)/SystemModel/UT_DefaultBinaryPathSelector.o     \
            $(OBJDIR_DEBUG)/Generated/Runner.o                             \

OBJ_RELEASE = \
              $(OBJDIR_RELEASE)/Utility/UT_Utility.o                       \
              $(OBJDIR_RELEASE)/Utility/UT_SVFVector.o                     \
              $(OBJDIR_RELEASE)/Utility/UT_BinaryVector.o                  \
              $(OBJDIR_RELEASE)/UT_Helpers/UT_SystemModelBuilder.o         \
              $(OBJDIR_RELEASE)/UT_Helpers/SystemModelBuilder.o            \
              $(OBJDIR_RELEASE)/SystemModel/UT_SystemModel.o               \
              $(OBJDIR_RELEASE)/SystemModel/UT_SystemModelCheckerVisitor.o \
              $(OBJDIR_RELEASE)/SystemModel/UT_Register.o                  \
              $(OBJDIR_RELEASE)/SystemModel/UT_SystemModelNode.o           \
              $(OBJDIR_RELEASE)/SystemModel/UT_PrettyPrinterVisitor.o      \
              $(OBJDIR_RELEASE)/SystemModel/UT_GmlPrinterVisitor.o         \
              $(OBJDIR_RELEASE)/SystemModel/UT_ConfigureVisitor.o          \
              $(OBJDIR_RELEASE)/SystemModel/UT_DefaultBinaryPathSelector.o \
              $(OBJDIR_RELEASE)/Generated/Runner.o


all: debug release

clean: clean_debug clean_release

before_debug:
> test -d ../bin/debug || mkdir -p ../bin/debug
> test -d $(OBJDIR_DEBUG)/Generated   || mkdir -p $(OBJDIR_DEBUG)/Generated
> test -d $(OBJDIR_DEBUG)/SystemModel || mkdir -p $(OBJDIR_DEBUG)/SystemModel
> test -d $(OBJDIR_DEBUG)/Utility     || mkdir -p $(OBJDIR_DEBUG)/Utility
> test -d $(OBJDIR_DEBUG)/UT_Helpers  || mkdir -p $(OBJDIR_DEBUG)/UT_Helpers

after_debug:

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
> $(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/Generated/Runner.o: Generated/Runner.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Generated/Runner.cpp -o $(OBJDIR_DEBUG)/Generated/Runner.o

$(OBJDIR_DEBUG)/UT_Helpers/SystemModelBuilder.o: UT_Helpers/SystemModelBuilder.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c UT_Helpers/SystemModelBuilder.cpp -o $(OBJDIR_DEBUG)/UT_Helpers/SystemModelBuilder.o

$(OBJDIR_DEBUG)/UT_Helpers/UT_SystemModelBuilder.o: UT_Helpers/UT_SystemModelBuilder.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c UT_Helpers/UT_SystemModelBuilder.cpp -o $(OBJDIR_DEBUG)/UT_Helpers/UT_SystemModelBuilder.o

$(OBJDIR_DEBUG)/SystemModel/UT_DefaultBinaryPathSelector.o: SystemModel/UT_DefaultBinaryPathSelector.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel/UT_DefaultBinaryPathSelector.cpp -o $(OBJDIR_DEBUG)/SystemModel/UT_DefaultBinaryPathSelector.o

$(OBJDIR_DEBUG)/SystemModel/UT_GmlPrinterVisitor.o: SystemModel/UT_GmlPrinterVisitor.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel/UT_GmlPrinterVisitor.cpp -o $(OBJDIR_DEBUG)/SystemModel/UT_GmlPrinterVisitor.o

$(OBJDIR_DEBUG)/SystemModel/UT_ConfigureVisitor.o: SystemModel/UT_ConfigureVisitor.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel/UT_ConfigureVisitor.cpp -o $(OBJDIR_DEBUG)/SystemModel/UT_ConfigureVisitor.o

$(OBJDIR_DEBUG)/SystemModel/UT_PrettyPrinterVisitor.o: SystemModel/UT_PrettyPrinterVisitor.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel/UT_PrettyPrinterVisitor.cpp -o $(OBJDIR_DEBUG)/SystemModel/UT_PrettyPrinterVisitor.o

$(OBJDIR_DEBUG)/SystemModel/UT_Register.o: SystemModel/UT_Register.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel/UT_Register.cpp -o $(OBJDIR_DEBUG)/SystemModel/UT_Register.o

$(OBJDIR_DEBUG)/SystemModel/UT_SystemModelNode.o: SystemModel/UT_SystemModelNode.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel/UT_SystemModelNode.cpp -o $(OBJDIR_DEBUG)/SystemModel/UT_SystemModelNode.o

$(OBJDIR_DEBUG)/SystemModel/UT_SystemModel.o: SystemModel/UT_SystemModel.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel/UT_SystemModel.cpp -o $(OBJDIR_DEBUG)/SystemModel/UT_SystemModel.o

$(OBJDIR_DEBUG)/SystemModel/UT_SystemModelCheckerVisitor.o: SystemModel/UT_SystemModelCheckerVisitor.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SystemModel/UT_SystemModelCheckerVisitor.cpp -o $(OBJDIR_DEBUG)/SystemModel/UT_SystemModelCheckerVisitor.o

$(OBJDIR_DEBUG)/Utility/UT_BinaryVector.o: Utility/UT_BinaryVector.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Utility/UT_BinaryVector.cpp -o $(OBJDIR_DEBUG)/Utility/UT_BinaryVector.o

$(OBJDIR_DEBUG)/Utility/UT_SVFVector.o: Utility/UT_SVFVector.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Utility/UT_SVFVector.cpp -o $(OBJDIR_DEBUG)/Utility/UT_SVFVector.o

$(OBJDIR_DEBUG)/Utility/UT_Utility.o: Utility/UT_Utility.cpp
> $(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Utility/UT_Utility.cpp -o $(OBJDIR_DEBUG)/Utility/UT_Utility.o

clean_debug:
> rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
> rm -rf ../bin/debug
> rm -rf $(OBJDIR_DEBUG)/Utility
> rm -rf $(OBJDIR_DEBUG)/UT_Helpers
> rm -rf $(OBJDIR_DEBUG)/SystemModel
> rm -rf $(OBJDIR_DEBUG)/Generated

before_release:
> test -d ../bin/release || mkdir -p ../bin/release
> test -d $(OBJDIR_RELEASE)/Generated   || mkdir -p $(OBJDIR_RELEASE)/Generated
> test -d $(OBJDIR_RELEASE)/SystemModel || mkdir -p $(OBJDIR_RELEASE)/SystemModel
> test -d $(OBJDIR_RELEASE)/Utility     || mkdir -p $(OBJDIR_RELEASE)/Utility
> test -d $(OBJDIR_RELEASE)/UT_Helpers  || mkdir -p $(OBJDIR_RELEASE)/UT_Helpers

after_release:

build_release: before_release out_release after_release

release: before_build build_release after_build

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
> $(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/Generated/Runner.o: Generated/Runner.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Generated/Runner.cpp -o $(OBJDIR_RELEASE)/Generated/Runner.o

$(OBJDIR_RELEASE)/UT_Helpers/SystemModelBuilder.o: UT_Helpers/SystemModelBuilder.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c UT_Helpers/SystemModelBuilder.cpp -o $(OBJDIR_RELEASE)/UT_Helpers/SystemModelBuilder.o

$(OBJDIR_RELEASE)/UT_Helpers/UT_SystemModelBuilder.o: UT_Helpers/UT_SystemModelBuilder.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c UT_Helpers/UT_SystemModelBuilder.cpp -o $(OBJDIR_RELEASE)/UT_Helpers/UT_SystemModelBuilder.o

$(OBJDIR_RELEASE)/SystemModel/UT_DefaultBinaryPathSelector.o: SystemModel/UT_DefaultBinaryPathSelector.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel/UT_DefaultBinaryPathSelector.cpp -o $(OBJDIR_RELEASE)/SystemModel/UT_DefaultBinaryPathSelector.o

$(OBJDIR_RELEASE)/SystemModel/UT_GmlPrinterVisitor.o: SystemModel/UT_GmlPrinterVisitor.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel/UT_GmlPrinterVisitor.cpp -o $(OBJDIR_RELEASE)/SystemModel/UT_GmlPrinterVisitor.o

$(OBJDIR_RELEASE)/SystemModel/UT_ConfigureVisitor.o: SystemModel/UT_ConfigureVisitor.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel/UT_ConfigureVisitor.cpp -o $(OBJDIR_RELEASE)/SystemModel/UT_ConfigureVisitor.o

$(OBJDIR_RELEASE)/SystemModel/UT_PrettyPrinterVisitor.o: SystemModel/UT_PrettyPrinterVisitor.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel/UT_PrettyPrinterVisitor.cpp -o $(OBJDIR_RELEASE)/SystemModel/UT_PrettyPrinterVisitor.o

$(OBJDIR_RELEASE)/SystemModel/UT_Register.o: SystemModel/UT_Register.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel/UT_Register.cpp -o $(OBJDIR_RELEASE)/SystemModel/UT_Register.o

$(OBJDIR_RELEASE)/SystemModel/UT_SystemModelNode.o: SystemModel/UT_SystemModelNode.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel/UT_SystemModelNode.cpp -o $(OBJDIR_RELEASE)/SystemModel/UT_SystemModelNode.o

$(OBJDIR_RELEASE)/SystemModel/UT_SystemModel.o: SystemModel/UT_SystemModel.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel/UT_SystemModel.cpp -o $(OBJDIR_RELEASE)/SystemModel/UT_SystemModel.o

$(OBJDIR_RELEASE)/SystemModel/UT_SystemModelCheckerVisitor.o: SystemModel/UT_SystemModelCheckerVisitor.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SystemModel/UT_SystemModelCheckerVisitor.cpp -o $(OBJDIR_RELEASE)/SystemModel/UT_SystemModelCheckerVisitor.o

$(OBJDIR_RELEASE)/Utility/UT_BinaryVector.o: Utility/UT_BinaryVector.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Utility/UT_BinaryVector.cpp -o $(OBJDIR_RELEASE)/Utility/UT_BinaryVector.o

$(OBJDIR_RELEASE)/Utility/UT_SVFVector.o: Utility/UT_SVFVector.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Utility/UT_SVFVector.cpp -o $(OBJDIR_RELEASE)/Utility/UT_SVFVector.o

$(OBJDIR_RELEASE)/Utility/UT_Utility.o: Utility/UT_Utility.cpp
> $(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Utility/UT_Utility.cpp -o $(OBJDIR_RELEASE)/Utility/UT_Utility.o

clean_release:
> rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
> rm -rf ../bin/release
> rm -rf $(OBJDIR_RELEASE)/Utility
> rm -rf $(OBJDIR_RELEASE)/UT_Helpers
> rm -rf $(OBJDIR_RELEASE)/SystemModel
> rm -rf $(OBJDIR_RELEASE)/Generated

.PHONY: before_build after_build before_debug after_debug clean_debug before_release after_release clean_release

