 Mast_Options:
   SIT_file_path: DUT.sit                   # [SIT] file used by the project
   Configuration_algorithm: last_or_default # One of [last_lazy, last_or_default, last_or_default_greedy] or one defined by a [plugin])
   Access_interface_protocol:               # When different to "SIT", it override the one define in [SIT] file
   Plugins:
     Files: []                              # List of plugin file(s) path (absolute or relative path)
     Directories: [Plugins]                 # Directory from where to load plugin files (absolute or relative path)
   Model_checking:
     Enable:    false                       # Enable/Disable model checking (provided it has been parsed successfully)
     File_path: ""                          # Optional file path (logged when no path when logged is enabled)
   Debug:
     Logging:
       Enable: false                        # Enable/Disable general logging
       Logger_Kind: std                     # One of [std, copy_all_on_cout, copy_errors_on_cerr]
       File_path:  "Mast.log"               # File path for logging (there is always a file logging when enabled)
       Shown_items: std                     # Any of [date, time, microseconds, level, thread_id, file_name, line_number, function_name, std, all]
       Level: info                          # One of [debug, info, warning, error]
     Model_GML_printing:
       Enable:  false                       # Enable/Disable printing of GML representation of the model state
       Moments:                             # Any of [after_model_parsing, before_configuration, after_configuration] (see bellow)
         - after_model_parsing
       File_path:   "MastModel.gml"         # Optional file path for GML graph printing
       Graph_name:  "DUT"                   # Optional graph name
       Options: std                         # Any of [default, identifiers, register_value, auto_value, protocol_name, selector_with_edge, selector_properties, selector_tables, selection_value, std, all]
     Model_textual_print:
       Enable:  false                       # Enable/Disable printing of textual representation of the model state
       Moments:                             # Any of [after_model_parsing, before_configuration, after_configuration] (see bellow)
         - after_model_parsing
       File_path: "MastModel.txt"           # Optional file path
       Options:  default                    # Any of [default, verbose, auto_value, protocol_name, selection_state, selection_value, selector_properties, ignored_nodes, std, all]
     Manager_activity:
       Enable:         false                # Enable/Disable logging and optionally reporting model state at specific point of manager activity
       File_base_name: "DUT"                # Path where pretty print and/or GML files are saved
       Options:        PDL_commands         # Any of [verbose, app_thread_creation, PDL_commands, data_cycles, std, all]
 Plugins_Options: ""                        # Defines plugins specific options (ignored by Mast)
